services:
  - type: web
    name: denr-server
    runtime: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
